---


- name: "Push nftalbes configuration file"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nftables.j2"
    dest: "/etc/nftables.conf"
    mode: 0755
    group: 'root'
    owner: 'root'
    lstrip_blocks: true
  become: true
  notify: "Restart nftables"