#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/linux_nftables

- name: 'Collecte ansible_distribution fact'
  ansible.builtin.setup:
    filter:
      - 'ansible_distribution'
  when:
    - ansible_distribution is not defined


- name: "Check file tasks for {{ ansible_distribution }} distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: file_stat
  delegate_to: 'localhost'

- name: "Load file tasks for {{ ansible_distribution }} distribution"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  no_log: true
  when:
    - file_stat.stat.exists

- name: 'No taksks for this distribution'
  ansible.builtin.debug:
    msg: 'No taksks for {{ ansible_distribution }} distribution'
  when:
    - not file_stat.stat.exists

- name: "Forcer l'exécution des handlers à la fin du rôle"
  ansible.builtin.meta: flush_handlers
